[package]
name = "rustodoro"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "2.0.0"
clap = { version = "4.5.4", features = ["derive"] }
rodio = "0.21.1"
crossterm = "0.29"
notify-rust = "4.11.7"
indicatif = "0.18.0"